### ISSUE TITLE
Łączenie z bazą danych PostgreSQL

### ISSUE THREAD

**Issue by pionierrrrr77777** [ilyashich/OnlineShop-PIK#16]

**Comment by jsputnik** [comment]
Czas trwania 2h30m: Próba łączenia PostgreSQL z aplikacją na Tomcacie - nie da się, Tomcat nie obsluguje JPA

**Comment by pionierrrrr77777** [comment]
Czas trwania 15h: Próba łączenia się z PostGreSQL z użyciem Hibernate - nie da się, Tomcat nie obsługuje JPA
Czas trwania 5h: Łączenie się z aplikacją na Tomcacie z PostGreSQL  - z użyciem sterownika JDBC
